### ISSUE TITLE
Remove use of maptools

### ISSUE THREAD

**Issue by rsbivand** [krennpa/SAEforest#2]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by krennpa** [comment]
Thank you for raising this issue. Future versions of this package will adapt the recommended changes.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

Please re-open until finished.

**Comment by rsbivand** [comment]
Removing retiring packages from DESCRIPTION, NAMESPACE and spurious roxygen tags, and running CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/krennpa/SAEforest/files/11352697/00check.log)

**Comment by rsbivand** [comment]
@krennpa See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.
